// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migratsiyalar to'g'ridan-to'g'ri ulanishni ishlatadi (DIRECT_URL);
    // agar berilmagan bo'lsa, DATABASE_URL'ga qaytadi (local dev).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
